root: true
extends:
  - 'plugin:vue/essential'
  - '@vue/standard'
parserOptions:
  parser: 'babel-eslint'
  ecmaVersion: 8
  sourceType: module
env:
  es6: true
  node: true
rules:
  comma-dangle: 0
  no-console: warn
  no-debugger: warn
  no-unused-vars: warn
  semi:
    - 2
    - always
  space-before-function-paren: 0
  vue/semi: off
